### ISSUE TITLE
同步的某个业务逻辑应该放在 models 还是 services

### ISSUE THREAD

**Issue by hbrls** [dvajs/dva-snippets#1]
比如 `models/user.state.data = []`

初次加载的时候比如 `fetchData` 看示例是放在 `services` 的

但如果做了某个 `post` 更新之后，只会返回当前被更新的单条数据，那么我要去 `data` 里面把这个单条数据找出来并更新掉，形如 `data.splice(index, 1, updated)`。我们把这个方法叫做 `updateStateAfterSuccessPost`，那么这个方法是应该放在 `models` 还是 `services`。

PS: 是在这里问这种问题吗？

**Comment by sorrycc** [comment]
services 只管从服务器端拉数据，业务逻辑放 effects 里。p.s. issue 统一提在 https://github.com/dvajs/dva/issues
